theme: jekyll-theme-slate
title: Concise
Description: How to write the no-nonsense version of your document. \n\n by Aleks Haecky (& made more concise by Katarina Stenstedt)
Author: by Aleks Haecky (& made more concise by Katarina Stenstedt)
